### NumPy Assignment:

Assignment 1: Array Creation and Manipulation

1.Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np

## Task 1
## Create a (5,5) array filled with integers between 1 and 20
arr1 = np.random.randint(1, 21, (5, 5))
print("Original 5x5 array:")
print(arr1)

## Replace all the elements in the third column with 1
arr1[:, 2] = 1
print("\nArray after replacing third column with 1:")
print(arr1)

## Task 2
## Create (4, 4) array with values from 1 to 16
arr2 = np.arange(1, 17).reshape(4, 4)
print("\nOriginal 4x4 array:")
print(arr2)

## Replace the diagonal elements with 0
arr2[np.arange(4), np.arange(4)] = 0
print("\nArray after replacing diagonal elements with 0:")
print(arr2)


Original 5x5 array:
[[17 10  1  9  5]
 [11 15  8  4 12]
 [ 8 16 10 19  3]
 [11 10 18 20  3]
 [14  2  3 12 16]]

Array after replacing third column with 1:
[[17 10  1  9  5]
 [11 15  1  4 12]
 [ 8 16  1 19  3]
 [11 10  1 20  3]
 [14  2  1 12 16]]

Original 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Array after replacing diagonal elements with 0:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


Assignment 2: Array Indexing and Slicing

1.Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

2.Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [3]:
## Task 1
## Create a array of shape (6, 6) with values from 1 to 36
arr1 = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Array:\n", arr1)

## Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns
sub_arr1 = arr1[2:5, 1:4]
print("\nSub-array of 3x3:\n", sub_arr1)

## Task 2
## Create a array of shape (5, 5) with random integers
arr2 = np.random.randint(0, 101, (5, 5))
print("\nOriginal 5x5 Array:\n", arr2)

## Extract the elements on border
sub_arr2 = arr2[1:-1, 1:-1]



Original 6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub-array of 3x3:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]

Original 5x5 Array:
 [[91 76 90 85 58]
 [15 65 50 63 91]
 [60 80 19 79 65]
 [77 27 47 49 76]
 [42 28 38 71 76]]


Assignment 3: Array Operations

1.Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [4]:
## Task 1
## Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, (3, 4))
array2 = np.random.randint(1, 11, (3, 4))

## Perform element-wise addition, subtraction, multiplication, and division
addition= array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2 

## Print the results
print("Array1: \n", array1)
print("Array2: \n", array2)
print("Addition: \n", addition)
print("Subtraction: \n", subtraction)
print("Multiplication: \n", multiplication)
print("Division: \n", division)

## Task 2
## Create a NumPy array of shape (4, 4) with values from 1 to 16
arr = np.arange(1, 17).reshape(4, 4)

## Row-wise sum
row_sum = np.sum(arr, axis=1)

## Column-wise sum
column_sum = np.sum(arr, axis=0)

## Print the results
print("Original Array: \n", arr)
print("Row_sum: \n", row_sum)
print("Column_sum: \n", column_sum)



Array1: 
 [[5 4 4 4]
 [9 7 2 6]
 [6 2 4 3]]
Array2: 
 [[ 2  4  9  3]
 [ 2  2  6  1]
 [ 3 10  4  2]]
Addition: 
 [[ 7  8 13  7]
 [11  9  8  7]
 [ 9 12  8  5]]
Subtraction: 
 [[ 3  0 -5  1]
 [ 7  5 -4  5]
 [ 3 -8  0  1]]
Multiplication: 
 [[10 16 36 12]
 [18 14 12  6]
 [18 20 16  6]]
Division: 
 [[2.5        1.         0.44444444 1.33333333]
 [4.5        3.5        0.33333333 6.        ]
 [2.         0.2        1.         1.5       ]]
Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row_sum: 
 [10 26 42 58]
Column_sum: 
 [28 32 36 40]


Assignment 4: Statistical Operations

1.Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

2.Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [5]:
## Task 1
## Create a NumPy array of shape (5, 5) filled with random integers
arr1 = np.random.randint(1, 11, size=(5, 5))

## Compute the mean, median, standard deviation, and variance of the array
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
variance= np.var(arr)

## Print the results
print("Random Array: \n", arr)
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std_dev)
print("Variance: ", variance)

## Task 2
## Create a NumPy array of shape (3, 3) with values from 1 to 9
arr2 = np.arange(1, 10).reshape(3, 3)

## Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1)
arr2_normalized = (arr2 - np.mean(arr2)) / np.std(arr2)

## Print the original and normalized arrays
print("Original Array: \n", arr2)
print("Normalized Array: \n", arr2_normalized)



Random Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Mean:  8.5
Median:  8.5
Standard Deviation:  4.6097722286464435
Variance:  21.25
Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


Assignment 5: Broadcasting

1.Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

2.Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [6]:
## Task 1
## Create a NumPy array of shape (3, 3) filled with random integers
arr_2d = np.random.randint(1, 11, size=(3, 3))

## Create a 1D array of shape (3,)
arr_1d = np.array([1,2,3])

## Add this to each row of the 2D array using broadcasting
result_add = arr_2d + arr_1d

## Print the array
print("2D Array:\n", arr_2d)
print("1D Array:\n", arr_1d)
print("Result of Addition:\n", result_add)

## Task 2
## Create a NumPy array of shape (4, 4) filled with random integers
arr_2d_b = np.random.randint(1, 11, size=(4, 4))

## Create a 1D array of shape (4,) 
arr_1d_b = np.array([5,10,15,20])

## Subtract from each column of the 2D array using broadcasting
result_subtract = arr_2d_b - arr_1d_b

## Print the array
print("2D Array:\n", arr_2d_b)
print("1D Array:\n", arr_1d_b)
print("Result of Subtraction:\n", result_subtract)


2D Array:
 [[ 7  8  6]
 [ 8  4  4]
 [ 1  1 10]]
1D Array:
 [1 2 3]
Result of Addition:
 [[ 8 10  9]
 [ 9  6  7]
 [ 2  3 13]]
2D Array:
 [[ 3  6 10  6]
 [ 1  4  4  2]
 [10  8  6  2]
 [10  3  4  4]]
1D Array:
 [ 5 10 15 20]
Result of Subtraction:
 [[ -2  -4  -5 -14]
 [ -4  -6 -11 -18]
 [  5  -2  -9 -18]
 [  5  -7 -11 -16]]


Assignment 6: Linear Algebra

1.Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

2.Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [7]:
## Task 1
## Create a NumPy array of shape (3, 3) representing a matrix
matrix=np.array([[1, 2, 3], 
               [4, 5, 6],
               [7, 8, 9]])

## Compute its determinant, inverse, and eigenvalues
det = np.linalg.det(arr)

# Inverse (only if determinant is not zero)
if det != 0:
    inverse = np.linalg.inv(matrix)
else:
    inverse = "Matrix is singular (no inverse)"

eigen = np.linalg.eigvals(arr)

## Print the results
print("Matrix:\n ", matrix)
print("Determinant: ", det)
print("Inverse:\n ", inverse)
print("Eigenvalues: ", eigen)

## Task 2
## Create two NumPy arrays of shape (2, 3) and (3, 2)
mat1=np.array([[1, 2, 3],
               [4, 5, 6]])
mat2=np.array([[7, 8],
               [9, 10],
               [11, 12]])
                
## Perform matrix multiplication using np.dot() or @ operator
result = np.dot(mat1, mat2)

## Print the result
print("Matrix 1 (2x3):\n", mat1 )
print("Matrix 2 (3x2):\n", mat2)
print("Matrix Multiplication Result (2x2):\n", result)

Matrix:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant:  0.0
Inverse:
  Matrix is singular (no inverse)
Eigenvalues:  [ 3.62093727e+01 -2.20937271e+00 -2.62410379e-15 -9.51420961e-17]
Matrix 1 (2x3):
 [[1 2 3]
 [4 5 6]]
Matrix 2 (3x2):
 [[ 7  8]
 [ 9 10]
 [11 12]]
Matrix Multiplication Result (2x2):
 [[ 58  64]
 [139 154]]


Assignment 7: Advanced Array Manipulation

1.Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

2.Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [8]:
## Task 1
## Create a NumPy array of shape (3, 3) with values from 1 to 9
arr1 = np.arange(1, 10).reshape(3, 3)

## Reshape to (1, 9)
reshaped_1_9 = arr1.reshape(1, 9)

## Reshape to (9, 1)
reshaped_9_1 = arr1.reshape(9, 1)

## Print the results
print("Original 3x3 Array:\n", arr1)
print("Reshaped to (1, 9):\n", reshaped_1_9)
print("Reshaped to (9, 1):\n", reshaped_9_1)

## Task 2
## Create a 5x5 array with random integers between 1 and 100
arr2 = np.random.randint(1, 101, size=(5, 5))

## Flatten the array
flattened = arr2.flatten()

## Reshape back to (5, 5)
reshaped_back = flattened.reshape(5, 5)

## Print the results
print("Original 5x5 Array:\n", arr2)
print("Flattened Array:\n", flattened)
print("Reshaped Back to (5, 5):\n", reshaped_back)

Original 3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped to (1, 9):
 [[1 2 3 4 5 6 7 8 9]]
Reshaped to (9, 1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Original 5x5 Array:
 [[84 26 97 57 42]
 [51 43 83 98 84]
 [93 13 59 67 55]
 [26 83 73 16 21]
 [ 1 88 69 48 95]]
Flattened Array:
 [84 26 97 57 42 51 43 83 98 84 93 13 59 67 55 26 83 73 16 21  1 88 69 48
 95]
Reshaped Back to (5, 5):
 [[84 26 97 57 42]
 [51 43 83 98 84]
 [93 13 59 67 55]
 [26 83 73 16 21]
 [ 1 88 69 48 95]]


Assignment 8: Fancy Indexing and Boolean Indexing

1.Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

2.Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [10]:
## Task 1
## Create a NumPy array of shape (5, 5) filled with random integers
arr = np.random.randint(1, 11, size=(5, 5))

## Use fancy indexing to extract the elements at the corners of the array
corners = arr[[0,0,4,4], [0,4,0,4]]

## Print the results
print("Original 5x5 Array:\n", arr)
print("Corner Elements:\n", corners)

## Task 2
## Create a (4,4) array with random integers
array2 = np.random.randint(1, 21, size=(4, 4))

## Boolean indexing to modify elements > 10
array2[array2 > 10] = 10

## Print the results
print("Original 4x4 Array:\n", array2)
print("Modified Array (elements >10 set to 10):\n", array2)


Original 5x5 Array:
 [[ 8  5  9  9 10]
 [ 9  3  7  9  5]
 [ 6  2  5  6  1]
 [10  8  8  6  3]
 [ 7  6  3  4  1]]
Corner Elements:
 [ 8 10  7  1]
Original 4x4 Array:
 [[10  2  8 10]
 [ 6 10 10  5]
 [10 10  3 10]
 [10  4 10  5]]
Modified Array (elements >10 set to 10):
 [[10  2  8 10]
 [ 6 10 10  5]
 [10 10  3 10]
 [10  4 10  5]]


Assignment 9: Structured Arrays

1.Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

2.Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [12]:
## Task 1
## Define a structured datatype
dtype1= np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f4')])

## Create a structured array
arr1 = np.array([('John', 25, 70.5),
                  ('Maria', 31, 60.0),
                  ('Bobz', 42, 80.0)], dtype=dtype1)

## Sort the age
sorted_age= np.sort(arr1['age'])

## Print the sorted array
print( "Sorted_age:\n", sorted_age)

## Task 2
## Define a structured datatype with fields x and y
dtype2 = np.dtype([('x', 'i4'), ('y', 'i4')])

## Create a structured array
arr2 = np.array([(1, 2),
                  (3, 4), 
                  (5, 6)], dtype=dtype2)

## Extract the x and y values
x_values = arr2['x'].astype(float)
y_values = arr2['y'].astype(float)

## Number of points
n = len(arr2)

# Compute pairwise Euclidean distances
print("Pairwise Euclidean Distances:")
for i in range(n):
    for j in range(i+1, n):
        dist = np.sqrt((x_values[i] - x_values[j])**2 + (y_values[i] - y_values[j])**2)
        print(f"Distance between point {i} and {j}: {dist:.2f}")


Sorted_age:
 [25 31 42]
Pairwise Euclidean Distances:
Distance between point 0 and 1: 2.83
Distance between point 0 and 2: 5.66
Distance between point 1 and 2: 2.83


Assignment 10: Masked Arrays

1.Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2.Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [19]:
import numpy as np
import numpy.ma as ma
## Task 1
## Create an array of shape (4,4) with random integers
arr1 = np.random.randint( 1, 30, (4, 4))

## Mask the elements greater than 10
masked1 = ma.masked_greater(arr1, 10)

## Compute the sum of unmasked elements
sum1 = np.sum(masked1)

## Print the results
print( "Original array: \n", arr1 )
print( "Masked array: \n", masked1 )
print( "Sum of unmasked elements: ", sum1 )

## Task 2
## Create an array of shape (3,3) with random integers
arr2 = np.random.randint( 1, 30, (3, 3))
print("\nOriginal array: \n", arr2 )

## Mask the diagonal elements
mask_diagonal = np.eye(3, dtype=bool)

## Create masked array
masked2 = ma.array(arr2, mask=mask_diagonal)
print("\nMasked Array (diagonal elements masked):\n", masked2)

## Compute mean of unmasked elements
mean_unmasked = masked2.mean()
print("\nMean of unmasked elements:", mean_unmasked)

## Replace masked (diagonal) values with mean
filled_array = masked2.filled(mean_unmasked)
print("\nFinal Array (diagonal replaced with mean):\n", filled_array)



Original array: 
 [[ 7 12 17 21]
 [25 18 19 10]
 [ 5 18  4 20]
 [15  6  4 14]]
Masked array: 
 [[7 -- -- --]
 [-- -- -- 10]
 [5 -- 4 --]
 [-- 6 4 --]]
Sum of unmasked elements:  36

Original array: 
 [[22 21 15]
 [11 25 15]
 [ 4 13 17]]

Masked Array (diagonal elements masked):
 [[-- 21 15]
 [11 -- 15]
 [4 13 --]]

Mean of unmasked elements: 13.166666666666666

Final Array (diagonal replaced with mean):
 [[13 21 15]
 [11 13 15]
 [ 4 13 13]]
